apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -prod
namespace: demo-app-prod

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

commonLabels:
  environment: production
