apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-app-prod

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml
  - route-patch.yaml
